import { useEffect, useContext } from "react";
import { AuthContext } from "../context/AuthContext";
import Head from "next/head";
import { useRouter } from "next/router";
import Upload from "../components/Upload";

export default function Home() {
  const router = useRouter();
  const { user, logout } = useContext(AuthContext);

  useEffect(() => {
    if (!user) {
      router.push("/auth");
    }
  }, [user]);

  return (
    <div className="min-h-screen min-w-full relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button
        onClick={logout}
        className="absolute bottom-4 right-5 px-4 py-2 text-white bg-red-600 rounded-md"
      >
        Logout
      </button>
      <Upload />
    </div>
  );
}
